apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: cloudcart-api

  template:
    metadata:
      labels:
        app: cloudcart-api

    spec:
      containers:
        - name: cloudcart-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: cloudcart-config

            - secretRef:
                name: cloudcart-secret

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}